# DeepLearning on Pytorch

### Assignment 1 

PyTorch is an open source deep learning framework built to be flexible and modular for research, with the stability and support needed for production deployment. It enables fast, flexible experimentation through a tape-based autograd system designed for immediate and python-like execution. With the release of PyTorch 1.4 adds new capabilities, including the ability to do fine grain build level customization for PyTorch Mobile, and new experimental features including support for model parallel training and Java language bindings. 

Below are some Tensor functions in PyTorch Library:

- full
- eye
- linspace
- add
- unbind

In [22]:
# Import torch and other required modules
import torch



## Function 1 - torch.full

In tensor.full we can set size of the tensor , type of input and value which needs to be inserted. 

Syntax :

torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

    Mandatory Parameters :

   - size = size of the tensor

   - fill_value = value to be filled with

In [23]:
# Example 1 
torch.full((3,5),11.1665111)

tensor([[11.1665, 11.1665, 11.1665, 11.1665, 11.1665],
        [11.1665, 11.1665, 11.1665, 11.1665, 11.1665],
        [11.1665, 11.1665, 11.1665, 11.1665, 11.1665]])

as you see in the above example i have taken size of the matrix in brackets(i.e 3,5) and fill_value as 11.1665111 .

In [24]:
# Example 2 - lets try dtype
a =torch.full((2,4),5,dtype=bool)
b= torch.full((2,4),0,dtype=bool)
print(a)
print(b)

tensor([[True, True, True, True],
        [True, True, True, True]])
tensor([[False, False, False, False],
        [False, False, False, False]])


as you see zero is considered as false 

In [25]:
# Example 3 - breaking 
a= torch.rand(1)
torch.full((2,3),out=a)

TypeError: full() received an invalid combination of arguments - got (tuple, out=Tensor), but expected one of:
 * (tuple of ints size, Number fill_value, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, Number fill_value, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


as we observe above , fill_value cannot take another tensor as an input 

    This function should be used when one wants to perform filling the tensors.

## Function 2 - torch.eye

This function creates an identity matrix . 


Syntax :


torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

    Mandatory Parameters:
- n = number of rows (default)
- m = number of columns 

In [26]:
# Example 1 
a=torch.eye(3)
b=torch.eye(2,4)
print(a)
print(b)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]])



If only one value then it creates n X n matrix.

In [27]:
# Example 2 
torch.eye(3,4,out=b)
print(b)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


As you observe above 3x4 martix leaves 4th column with zeros. and the output is saved in 'd'

In [28]:
# Example 3 - breaking 
torch.eye(3.4)

TypeError: eye(): argument 'n' (position 1) must be int, not float

eye function does allow float values

    This function can be used to create 2D tensor Identity Martix.

## Function 3 - linspace


linspace seperates a tensor in specified amount of parts .
after first example things will be more clear .

Syntax :


torch.linspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

    Mandatory Paarameters 
 - start = starting number of tensor 
 - end = ending number of tensor 
 - steps = number of steps/space required

In [29]:
# Example 1 -
torch.linspace(1, 10)

tensor([ 1.0000,  1.0909,  1.1818,  1.2727,  1.3636,  1.4545,  1.5455,  1.6364,
         1.7273,  1.8182,  1.9091,  2.0000,  2.0909,  2.1818,  2.2727,  2.3636,
         2.4545,  2.5455,  2.6364,  2.7273,  2.8182,  2.9091,  3.0000,  3.0909,
         3.1818,  3.2727,  3.3636,  3.4545,  3.5455,  3.6364,  3.7273,  3.8182,
         3.9091,  4.0000,  4.0909,  4.1818,  4.2727,  4.3636,  4.4545,  4.5455,
         4.6364,  4.7273,  4.8182,  4.9091,  5.0000,  5.0909,  5.1818,  5.2727,
         5.3636,  5.4545,  5.5455,  5.6364,  5.7273,  5.8182,  5.9091,  6.0000,
         6.0909,  6.1818,  6.2727,  6.3636,  6.4545,  6.5455,  6.6364,  6.7273,
         6.8182,  6.9091,  7.0000,  7.0909,  7.1818,  7.2727,  7.3636,  7.4545,
         7.5455,  7.6364,  7.7273,  7.8182,  7.9091,  8.0000,  8.0909,  8.1818,
         8.2727,  8.3636,  8.4545,  8.5455,  8.6364,  8.7273,  8.8182,  8.9091,
         9.0000,  9.0909,  9.1818,  9.2727,  9.3636,  9.4545,  9.5455,  9.6364,
         9.7273,  9.8182,  9.9091, 10.00

As you see the above output . numbers from 1 to 10 is divided into equal 100 parts(because by default steps are set to 100) 

In [30]:
# Example 2 
torch.linspace(start=-10, end=10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

starts from -10 to 10 which is divided into 5 parts


In [31]:
# Example 3 - breaking 
torch.linspace(start=10,end=-10.55,steps =23.5)


TypeError: linspace(): argument 'steps' must be int, not float

    torch.linspace is used to create a 1D equally spaced tensor between the values start and end with spec

## Function 4 - torch.add

The add function returns a new tensor which indexes the input tensor along dimension dim using the entries in index which is a LongTensor.

Syntax :


torch.add(input, other, out=None)

    Mandatory Parameters
 - input = input tensor
 - other = the number to be added to each element of input
 

In [32]:
# Example 1 - 
a= torch.rand(5)
torch.add(a,5)

tensor([5.8777, 5.4623, 5.3885, 5.6192, 5.0629])

we are taking input as a.tensor and adding 5 to every element to it .

In [33]:
# Example 2 - 
a=torch.rand(5)
b=torch.rand(5)
print(a)
print(b)
torch.add(a,b)

tensor([0.5538, 0.3309, 0.4718, 0.3165, 0.7022])
tensor([0.3271, 0.2434, 0.1647, 0.9096, 0.7565])


tensor([0.8810, 0.5743, 0.6365, 1.2261, 1.4586])

adding a.tensor and b.tensor 

In [34]:
# Example 3 - breaking
a=torch.rand(5)
b=torch.rand(5)
print(a)
print(b)
torch.add(a,b,4)

tensor([0.2302, 0.9061, 0.0222, 0.6347, 0.0127])
tensor([0.8013, 0.5106, 0.8113, 0.7058, 0.3310])


TypeError: add() takes 2 positional arguments but 3 were given

tried to add 4 to the added tensor but failed 

    This function can be used when we want to increase each and every element to be incremented by specific value 

## Function 5 - torch.unbind

Removes a tensor dimension 

Syntax :

    
torch.unbind(input, dim=0)
    
    Mandatory Parameters
 - input = Which tensor to unbind
 - dim = number of dimensions to be removed
 

In [35]:
# Example 1
a= torch.full((3,4),5)
print(a)
torch.unbind(a)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


(tensor([5., 5., 5., 5.]), tensor([5., 5., 5., 5.]), tensor([5., 5., 5., 5.]))

we observe that the tensor now has zero dimension as we didnt set any 'dim' it is '0' at default

In [36]:
# Example 2 
a= torch.eye(2,3)
print(a)
torch.unbind(a,dim=-1)

tensor([[1., 0., 0.],
        [0., 1., 0.]])


(tensor([1., 0.]), tensor([0., 1.]), tensor([0., 0.]))

Explanation about example

In [37]:
# Example 3 - breaking
a= torch.eye(10)
print(a)
torch.unbind(a,dim=4)


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 4)

Dimension range is accepted of [-2,1]. 

    Returns a tuple of all slices along a given dimension, already without it.

## Conclusion

These are the five basic functions of Pytorch and please refer the refernce links below for futher learning . Tune in for next notebook on Linear Regression.

## Reference Links

* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://pytorch.org/docs/master/torch.html

In [38]:
!pip install jovian --upgrade --quiet

In [39]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
